#!/usr/bin/env python3


import argparse
import os
import subprocess
import sys

import visualizer


_COMMANDS = {
    "build": "compile",
    "push": "flash",
}

_KEYBOARDS = {
    "corne": "crkbd/rev1",
    "cornelius": "foostan/cornelius",
    "ferris": "ferris/sweep",
    "kyria": "splitkb/kyria/rev1",
}


def qmk(cmd, targets):
    for target in targets:
        subprocess.check_call(["qmk", cmd, "-kb", target])


def show(render, targets):
    for target in targets:
        render(target)


def main():
    parser = argparse.ArgumentParser(description="Build util for QMK")
    parser.add_argument("command")
    parser.add_argument("keyboard")
    args = parser.parse_args()

    command = _COMMANDS.get(args.command, args.command)

    if args.keyboard == "all":
        targets = _KEYBOARDS.values()
    else:
        targets = [_KEYBOARDS.get(args.keyboard, args.keyboard)]

    try:
        if command == "show":
            show(visualizer.render_ascii, targets)
        elif command == "svg":
            show(visualizer.render_svg, targets)
        else:
            qmk(command, targets)
    except subprocess.CalledProcessError:
        return 1
    except KeyboardInterrupt:
        print()
        print("Aborting.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
