# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orchestrate or schedule a set of jobs
jobs:
  run:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: apt update && apt install -y gcc-8 unzip wget python3 zip gcc-avr binutils-avr avr-libc dfu-programmer dfu-util gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
      - run: sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
      - run: avr-gcc --version; gcc -v
      - run: ./init.sh
      - run: ./qmk build ergodox_ez
      - run: ./qmk show ergodox_ez
      - run: ./qmk build levinson
      - run: ./qmk show levinson
workflows:
  version: 2
  run_wf:
    jobs:
      - run
